#!/usr/bin/env bun
/**
 * imgkit Bun Executable Setup Helper
 *
 * Generates the necessary files to use imgkit with `bun build --compile`
 *
 * Usage: bunx imgkit-bun-setup [output-dir]
 */

import { existsSync, mkdirSync, writeFileSync, copyFileSync } from "fs";
import { join, dirname } from "path";

const platform = process.platform;
const arch = process.arch;

// Determine the correct package and binary
let targetName: string;
let packageSuffix: string;

switch (platform) {
  case "darwin":
    targetName = arch === "arm64" ? "darwin-arm64" : "darwin-x64";
    packageSuffix = targetName;
    break;
  case "linux":
    const isMusl = existsSync("/etc/alpine-release");
    if (arch === "arm64") {
      targetName = isMusl ? "linux-arm64-musl" : "linux-arm64-gnu";
    } else {
      targetName = isMusl ? "linux-x64-musl" : "linux-x64-gnu";
    }
    packageSuffix = targetName;
    break;
  case "win32":
    targetName = arch === "arm64" ? "win32-arm64-msvc" : "win32-x64-msvc";
    packageSuffix = arch === "arm64" ? "windows-arm64" : "windows-x64";
    break;
  default:
    console.error(`Unsupported platform: ${platform}-${arch}`);
    process.exit(1);
}

const binaryName = `image-turbo.${targetName}.node`;
const optionalPackageName = `imgkit-${packageSuffix}`;

const outputDir = process.argv[2] || "dist";

console.log(`
╔══════════════════════════════════════════════════════════════╗
║              imgkit Bun Executable Setup                     ║
╚══════════════════════════════════════════════════════════════╝

Platform: ${platform}-${arch}
Package:  ${optionalPackageName}
Binary:   ${binaryName}
Output:   ${outputDir}/
`);

// Find the native binary
const possiblePaths = [
  join(process.cwd(), "node_modules", optionalPackageName, binaryName),
  join(process.cwd(), "node_modules", "imgkit", binaryName),
  join(dirname(import.meta.dir), "..", optionalPackageName, binaryName),
];

let sourceBinary: string | null = null;
for (const p of possiblePaths) {
  if (existsSync(p)) {
    sourceBinary = p;
    break;
  }
}

if (!sourceBinary) {
  console.error(`❌ Could not find native binary. Tried:`);
  possiblePaths.forEach(p => console.error(`   - ${p}`));
  console.error(`\nMake sure imgkit is installed: bun add imgkit`);
  process.exit(1);
}

console.log(`✓ Found native binary: ${sourceBinary}`);

// Create output directory
if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
}

// Copy the native binary
const destBinary = join(outputDir, binaryName);
copyFileSync(sourceBinary, destBinary);
console.log(`✓ Copied binary to: ${destBinary}`);

// Generate wrapper script
const wrapperScript = `#!/bin/bash
# Auto-generated by imgkit-bun-setup
# Run your Bun executable with the correct native module path

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
export IMGKIT_NATIVE_PATH="\${SCRIPT_DIR}/${binaryName}"
exec "\${SCRIPT_DIR}/\${1:-app}" "\${@:2}"
`;

const wrapperPath = join(outputDir, "run.sh");
writeFileSync(wrapperPath, wrapperScript, { mode: 0o755 });
console.log(`✓ Created wrapper script: ${wrapperPath}`);

// Generate instructions
console.log(`
╔══════════════════════════════════════════════════════════════╗
║                    Build Instructions                        ║
╚══════════════════════════════════════════════════════════════╝

1. Build your executable:
   bun build --compile --outfile ${outputDir}/app your-entry.ts

2. Run using the wrapper script:
   ${outputDir}/run.sh app

   Or set the environment variable manually:
   IMGKIT_NATIVE_PATH=./${binaryName} ./${outputDir}/app

3. For distribution, include these files:
   ${outputDir}/
   ├── app                    (your compiled executable)
   ├── ${binaryName}  (native module)
   └── run.sh                 (optional wrapper script)

Done! ✓
`);
